### ISSUE TITLE
Could you post some pics about Jelly Robot?

### ISSUE THREAD

**Issue by littleggghost** [AMABerkeley/jelly#2]
Hi, there
After I read your introduction, I think the Jelly Robot should be a quadruped. I'm really interested because you are a team from Berkeley and  I do like quadruped myself.
So are there some pics or videos about your quadruped?

**Comment by brentyi** [comment]
Jelly's a work-in-progress, but here are some pictures! :)

![image](https://user-images.githubusercontent.com/6992947/57610849-6aa64780-7526-11e9-93a8-ed7ffcb89444.png)
(render from [jelly_mechanical](https://github.com/AMABerkeley/jelly_mechanical))

![image](https://user-images.githubusercontent.com/6992947/57610840-6548fd00-7526-11e9-9824-6006066d492a.png)

**Comment by littleggghost** [comment]
Wow! Really cool!
Hope your team can video it on YouTube as soon.
Cheers up!

**Comment by littleggghost** [comment]
And, when the video of Jelly expected to be released? In three month?
